services: #postar imagem
  app01:
    build:
      context: ..
      dockerfile: dockerfile
    hostname: app01
    network_mode: host
    environment:
      HTTP_PORT: 8080
    deploy:
      resources:
        limits:
          cpus: "0.37"
          memory: "60MB"
  app02:
    build:
      context: ..
      dockerfile: dockerfile
    hostname: app02
    network_mode: host
    environment:
      HTTP_PORT: 8081
    deploy:
      resources:
        limits:
          cpus: "0.37"
          memory: "60MB"

  database:
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_PASSWORD: "local_password"
    network_mode: host
    volumes:
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.56"
          memory: "400MB"
  nginx:
    image: nginx:1.25.4-alpine
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app01
      - app02
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB" # 60MB

#implementar limites de memoria: 550 mb e de cpu: 1.5 cpus
