services: #postar imagem
  app01:
    build:
      context: ..
      dockerfile: dockerfile
    hostname: app01
    network_mode: host
    environment:
      HTTP_PORT: 8080

  app02:
    build:
      context: ..
      dockerfile: dockerfile
    hostname: app02
    network_mode: host
    environment:
      HTTP_PORT: 8081

  database:
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_PASSWORD: "local_password"
    network_mode: host
    volumes:
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql
  nginx:
    image: nginx:1.25.4-alpine
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app01
      - app02
    network_mode: host
#implementar limites de memoria e de cpu
